import { NalufxTheme } from "./themes/index.slint";

export component StateLayer inherits TouchArea {
    in-out property <length> border-radius <=> i-container.border-radius;
    in-out property <brush> background <=> i-container.background;

    states [
        pressed when root.pressed : {
            i-container.opacity: 0.1618;
        }
    ]

    i-container := Rectangle {
        width: 100%;
        height: 100%;
        background: NalufxTheme.palette.black;
        opacity: 0.0;

        animate background { duration: NalufxTheme.durations.medium; }
    }
}