

import { Theme } from "../theme.slint";

export component StateLayer inherits TouchArea {
    in-out property <length> border-radius <=> i-container.border-radius;
    in-out property <brush> background <=> i-container.background;

    width: 100%;
    height: 100%;

    states [
        pressed when root.pressed : {
            i-container.opacity: 0.12;
        }
    ]

    i-container := Rectangle {
        width: 100%;
        height: 100%;
        background: Theme.palette.pure-black;
        opacity: 0.0;

        animate background { duration: Theme.durations.medium; }
    }
}