import { Theme } from "../../theme.slint";

export component Card inherits Rectangle {
    in property <string> title;
    in property <string> description;
    in property <image> image-source;
    in property <bool> has-image;
    callback clicked <=> i-touch-area.clicked;
    preferred-width: 200px;
    preferred-height: 200px;
    in property <length> corner-radius: 10px;
    in property <color> background-color: Theme.palette.white;
    in property <color> hover-background-color: background-color.darker(33%);
    in property <color> pressed-background-color: background-color.darker(66%);
    in property <duration> transition-duration: Theme.durations.fast;

    border-radius: root.corner-radius;
    background: background-color;
    clip: true;

    states [
        pressed when i-touch-area.pressed: {
            background: pressed-background-color;
        }
        hover when i-touch-area.has-hover: {
            background: hover-background-color;
        }
    ]

    animate background { duration: transition-duration; }

    VerticalLayout {
        spacing: 0px;

        if (has-image) : Rectangle {
            width: parent.width;
            height: title != "" || description != "" ? parent.height / 2 : parent.height;
            clip: true;
            border-top-left-radius: root.corner-radius;
            border-top-right-radius: root.corner-radius;
            i-image := Image {
                width: parent.width;
                height: parent.height;
                source: root.image-source;
                image-fit: cover;
                image-rendering: smooth;
            }
        }

        if (title != "" || description != "") : VerticalLayout {
            padding: 12px;
            spacing: 4px;

            if (title != "") : i-title := Text {
                text: root.title;
                color: Theme.palette.black;
                font-size: 16px;
                font-weight: 700;
                wrap: word-wrap;
            }

            if (description != "") : i-description := Text {
                text: root.description;
                color: Theme.palette.black;
                font-size: 12px;
                font-weight: 400;
                wrap: word-wrap;
            }
        }
    }

    i-touch-area := TouchArea { }
}