/// A struct defining a set of colors used in the theme.
export struct Colors {
    /// The primary color.
    primary: brush,

    /// A variant of the primary color.
    primary-variant: brush,

    /// The color used on top of the primary color.
    on-primary: brush,

    /// The secondary color.
    secondary: brush,

    /// A variant of the secondary color.
    secondary-variant: brush,

    /// The tertiary color.
    tertiary: brush,

    /// The color used on top of the tertiary color.
    on-tertiary: brush,

    /// The color used on top of the secondary color.
    on-secondary: brush,

    /// The background color.
    background: brush,

    /// The color used on top of the background color.
    on-background: brush,

    /// The surface color.
    surface: brush,

    /// The color used on top of the surface color.
    on-surface: brush,

    /// The error color.
    error: brush,

    /// The color used on top of the error color.
    on-error: brush,

    /// A transparent color.
    transparent: brush,
}

/// A global set of default colors.
export global DefaultColors {
    /// The color palette used in the theme.
    out property <Colors> palette: {
        primary: #6200EE,
        primary-variant: #3700B3,
        on-primary: #FFFFFF,
        secondary: #03DAC6,
        secondary-variant: #018786,
        tertiary: #FFD600,
        on-tertiary: #000000,
        on-secondary: #000000,
        background: #FFFFFF,
        on-background: #000000,
        surface: #FFFFFF,
        on-surface: #000000,
        error: #B00020,
        on-error: #FFFFFF,
        transparent: #00000000,
    };
}
