import { Colors, DefaultColors } from "color_scheme.slint";
import { Typo, DefaultFonts } from "font_scheme.slint";
import { Duration, DefaultDurations } from "duration_scheme.slint";

/// The theme of the Nalufx UI
export global NalufxTheme {
    /// The color palette of the theme
    in property <Colors> palette: DefaultColors.palette;
    /// The typography of the theme
    in property <Typo> typography: DefaultFonts.typography;
    /// The duration scheme of the theme
    in property <Duration> durations: DefaultDurations.durations;
}