import { Colors, DefaultColors, Gradients, DefaultGradients } from "color_scheme.slint";
import { Duration, DefaultDurations } from "duration_scheme.slint";
import { ScreenType, DefaultScreenTypes } from "screen_scheme.slint";
import { Space, DefaultSpaces } from "space_scheme.slint";
import { Typo, DefaultFonts } from "font_scheme.slint";

/// The theme of the Nalufx UI
export global NalufxTheme {
    /// The color palette of the theme
    in property <Colors> palette: DefaultColors.palette;
    /// The typography of the theme
    in property <Typo> typography: DefaultFonts.typography;
    /// The duration scheme of the theme
    in property <Duration> durations: DefaultDurations.duration;
    /// The space scheme of the theme
    in property <Space> spaces: DefaultSpaces.space;
    /// The gradient scheme of the theme
    in property <Gradients> gradients: DefaultGradients.type;
    /// The screen type of the theme
    in property <ScreenType> screen: DefaultScreenTypes.screenType;
}