import { ButtonCore } from "button_core.slint";
import { Theme } from "../../theme.slint";

/**
 * Button Component
 *
 * This component extends ButtonCore and adds theme-specific styling
 * and additional functionality.
 */
export component Button inherits ButtonCore {
    /**
     * The minimum height of the button.
     */
    minHeight: 44pt;

    /**
     * The minimum width of the button.
     */
    minWidth: 44pt;


    /**
     * The height of the button.
     */
    height: 44pt;

    /**
     * The width of the button.
     */
    width: 44pt;

    /**
     * The border radius of the button.
     * Set to create a circular button when width and height are equal.
     */
    borderRadius: max(self.width, self.height) / 2;

    /**
     * The default text color of the button.
     */
    textColor: Theme.palette.white;

    /**
     * The text color when the button is hovered.
     */
    hoverTextColor: Theme.palette.white;

    /**
     * The font size of the button text.
     */
    fontSize: 16px;

    /**
     * The background of the button.
     */
    background: Theme.palette.nalufx-twilight-gradient;

    /**
     * The padding around the button content.
     */
    padding: 15px;

    // Apply padding to the internal layout
    Rectangle {
        HorizontalLayout {
            padding-left: root.padding;
            padding-right: root.padding;
            padding-top: root.padding;
            padding-bottom: root.padding;
        }
    }
}