import { ButtonCore } from "button_core.slint";
import { Theme } from "../../theme.slint";
import { StateLayer } from "../../components/state_layer.slint";

/**
 * IconButton Component
 *
 * This component inherits from ButtonCore and adds icon-specific properties
 * and additional functionality.
 */
export component IconButton inherits ButtonCore {
    /**
     * Property: icon
     * Type: image
     * Description: The icon displayed on the button.
     */
    in property <image> icon <=> i-icon.source;

    /**
     * Event: clicked
     * Description: Event triggered when the button is clicked.
     */
    // callback clicked <=> i-touch-area.clicked;

    vertical-stretch: 0;
    horizontal-stretch: 0;
    min-width: 44pt;
    min-height: 44pt;
    borderRadius: 22pt;

    states [
        /**
         * State: disabled
         * Description: The state when the button is disabled.
         */
        disabled when !root.enabled : {
            opacity: 0.25;
        }
        /**
         * State: pressed
         * Description: The state when the button is pressed.
         */
        pressed when i-touch-area.pressed : {
            i-icon.colorize: Theme.palette.purple;
        }
    ]

    GridLayout {
        padding: 4px;

        /**
         * Element: i-icon
         * Description: The image element representing the icon.
         */
        i-icon := Image {
            colorize: Theme.palette.white;
            animate colorize { duration: Theme.durations.medium; }
        }
    }

    i-touch-area := TouchArea {
        width: 100%;
        height: 100%;
    }
}
