import { Theme } from "../theme.slint";
import { StateLayer } from "../components/state_layer.slint";

export component Button {
    in property <string> text;
    in property <bool> enabled <=> i-state-layer.enabled;
    callback clicked <=> i-state-layer.clicked;

    min-height: 32px;
    min-width: 32px;

    i-container := Rectangle {
        background: Theme.palette.heliotrope-gradient;
        border-radius: max(self.width, self.height) / 2;
        width: 50px;
        height: 50px;

        i-state-layer := StateLayer {
            width: parent.width;
            height: parent.height;
            border-radius: parent.border-radius;
        }

        HorizontalLayout {
            alignment: center;
            padding: 15px;
            i-text := Text {
                text: root.text;
                color: Theme.palette.white;
                font-size: 16px;
                visible: root.text != "";
            }
        }
    }
}