import { NalufxTheme } from "../components/themes/index.slint";

export component GroupBox {
    in property <string> title <=> i-title.text;
    in property <length> spacing;

    layout := VerticalLayout {
        spacing: NalufxTheme.spaces.large;
        max-width: root.width;
        max-height: root.height;

        i-title := Text {
            horizontal-alignment: left;
            color: NalufxTheme.palette.labelColor;
            font-size: NalufxTheme.typography.label.size.desktop;
            font-weight: NalufxTheme.typography.label.weight;
        }

        i-layout := HorizontalLayout {
            spacing: root.spacing;

            @children
        }
    }
}