import { NalufxTheme } from "../components/themes/index.slint";
import { StateLayer } from "../components/state_layer.slint";
import { ScrollView } from "scroll_view.slint";
import { StateLayer } from "../components/state_layer.slint";

export component Item {
    in property <string> text <=> i-text.text;
    in property <bool> has-separator;

    callback clicked <=> i-touch-area.clicked;

    min-height: 40px;

    i-container := Rectangle {
        background: NalufxTheme.palette.underPageBackgroundColor;
    }

    i-touch-area := TouchArea { }

    HorizontalLayout {
        padding-left: NalufxTheme.spaces.medium;
        padding-top: NalufxTheme.spaces.medium;
        padding-bottom: NalufxTheme.spaces.medium;
        padding-right: NalufxTheme.spaces.medium;
        spacing: NalufxTheme.spaces.medium;

        i-text := Text {
            horizontal-stretch: 1;
            color: NalufxTheme.palette.labelColor;
            font-size: NalufxTheme.typography.header.size.desktop;
            font-weight: NalufxTheme.typography.header.weight;
            vertical-alignment: center;
        }

        @children
    }

    if (has-separator): Rectangle {
        width: parent.width - 2 * NalufxTheme.spaces.medium;
        height: 1px;
        x: NalufxTheme.spaces.medium;
        y: parent.height - self.height;
        background: NalufxTheme.palette.underPageBackgroundColor;
        opacity: 0.25;
    }
}

export component ItemGroupBox {
    in property <string> title <=> i-title.text;

    VerticalLayout {
        HorizontalLayout {
            padding: NalufxTheme.spaces.medium;

            i-title := Text {
                color: NalufxTheme.palette.labelColor;
                font-size: NalufxTheme.typography.header.size.desktop;
                font-weight: NalufxTheme.typography.header.weight;
            }
        }

        Rectangle {
            background: NalufxTheme.palette.transparent;
            border-radius: 4px;

            VerticalLayout {
                @children
            }
        }
    }
}
