
import { NalufxTheme } from "../components/themes/index.slint";
import { Theme } from "../theme.slint";

component Bubble inherits Rectangle {
    in property <bool> selected;

    states [
        selected when selected : {
            background: NalufxTheme.palette.white;
        }
    ]

    min_width: 5px;
    min_height: 5px;
    border-radius: max(self.width, self.height) / 2;
    background: NalufxTheme.palette.windowBackgroundColor;

    i-touch-area := TouchArea {}
}

export component Pagination {
    in property <int> count;
    in property <int> selected_index;

    callback clicked <=> i-touch-area.clicked;

    min-height: 26px;
    vertical-stretch: 0;

    VerticalLayout {
        alignment: center;

        HorizontalLayout {
            alignment: center;
            spacing: Theme.spaces.small;

            for index in count : Bubble {
                selected: index == selected-index;
            }
        }
    }

    i-touch-area := TouchArea {}
}