import { NalufxTheme } from "../components/themes/index.slint";

component ValueDelegate {
    in property <bool> active;
    in property <string> title <=> i-title.text;
    in property <string> unit <=> i-unit.text;
    in property <float> value;
    in property <bool> alternative-colors;

    private property <float> display-value;

    states [
        active when active : {
            display-value: value;

            in {
                animate display-value { duration: NalufxTheme.durations.slow; }
            }
        }
    ]

    HorizontalLayout {
        spacing: 15px;

        Rectangle {
            min_width: 2px;
            background: alternative-colors ? NalufxTheme.palette.primary-variant : NalufxTheme.palette.secondary-variant;
            horizontal-stretch: 0;
        }

        VerticalLayout {
            alignment: center;
            horizontal-stretch: 1;

            i-title := Text {
                color: alternative-colors ? NalufxTheme.palette.primary-variant : NalufxTheme.palette.secondary-variant;
                font-size: NalufxTheme.typography.header-item.size.desktop;
                font-weight: NalufxTheme.typography.label.weight;
            }

            HorizontalLayout {
                alignment: start;
                spacing: 5px;

                i-unit := Text {
                    y: NalufxTheme.spaces.small;
                    vertical-alignment: center;
                    color: alternative-colors ? NalufxTheme.palette.primary-accent : alternative-colors ? NalufxTheme.palette.primary-accent : NalufxTheme.palette.secondary-accent;
                    font-weight: NalufxTheme.typography.label.weight;
                }

                Text {
                    color: NalufxTheme.palette.labelColor;
                    text: round(display-value * 100) / 100;
                    font-size: NalufxTheme.typography.value.size.desktop;
                    font-weight: NalufxTheme.typography.value.weight;
                    vertical-alignment: center;
                }
            }
        }
    }
}

export struct Value {
    title: string,
    value: float,
    unit: string,
}

export component ValueDisplay {
    in property <bool> alternative-colors;
    in property <[Value]> model;
    in property <bool> active;
    in property <bool> transparent-background;
    in property <bool> vertical;

    min-height: 70px;

    i-container := Rectangle {
        visible: !transparent-background;
        width: 100%;
        height: 100%;
        border-radius: 4px;
        background: NalufxTheme.palette.underPageBackgroundColor;
    }

    if(model.length > 0 && !vertical) : HorizontalLayout {
        x: 15px;
        width: parent.width - 30px;
        height: 100%;
        padding-top: 10px;
        padding-bottom: 10px;

        for value in root.model : ValueDelegate {
            width: parent.width / model.length;
            horizontal-stretch: 1;
            alternative-colors: root.alternative-colors;
            title: value.title;
            value: value.value;
            unit: value.unit;
            active: root.active;
        }
    }

    if(model.length > 0 && vertical) : VerticalLayout {
        for value in root.model : ValueDelegate {
            vertical-stretch: 1;
            alternative-colors: root.alternative-colors;
            title: value.title;
            value: value.value;
            unit: value.unit;
            active: root.active;
        }
    }
}
