import { Images } from "../../images.slint";
import { NalufxTheme } from "../../components/themes/index.slint";
import { StateLayer } from "../../components/state_layer.slint";
import { FloatButton} from "../../components/button/float_button.slint";

export component MenuButton {
    callback clicked;

    in-out property <bool> internal_toggled: false;

    opacity: root.visible ? 1.0 : 0.0;

    animate opacity { duration: NalufxTheme.durations.fast; }

    i-container := Rectangle {
        background: NalufxTheme.palette.system-blue;
        border-radius: max(self.width, self.height) / 2;
        width: 100%;
        height: 100%;
        FloatButton {
                padding: 10px;
                horizontal-stretch: 0;
                icon: root.internal_toggled ? Images.carret-bottom : Images.carret-top;
                clicked => {
                    root.internal_toggled = !root.internal_toggled;
                root.clicked();
                }
            }
        // VerticalLayout {
        //     padding-left: 20px;
        //     padding-right: 20px;
        //     padding-top: 20px;
        //     padding-bottom: 20px;
        //     spacing: 11px;
        //     alignment: center;
        //     vertical-stretch: 1;
        //     Image {
        //         source: root.internal_toggled ? Images.carret-bottom : Images.carret-top;
        //         width: 27px;
        //         height: 16px;
        //     }
        // }
    }

    i-state-layer := StateLayer {
        border-radius: i-container.border-radius;
        clicked => {
            root.internal_toggled = !root.internal_toggled;
            root.clicked();
        }
    }
}
