

import { MenuOverviewAdapter } from "menu_overview.slint";
import { Settings, SettingsAdapter } from "watchlist.slint";
import { Theme } from "../../theme.slint";

export { MenuOverviewAdapter, SettingsAdapter }

export global MenuPageAdapter {
    in property <[StandardListViewItem]> model: [
        { text: "Production & Self-consumption"},
        { text: "Usage"},
        { text: "Balance"},
    ];
    in-out property <int> selected-index;
}

export component MenuPage {
    in-out property <int> current-index;

    callback page-changed(/* index */ int);
    callback close;

    private property <bool> show-settings;

    function back() {
        current-index = 0;
    }

    Rectangle {
        x: -parent.width * current-index;
        width: 2 * parent.width;
        clip: true;

        animate x { duration: Theme.durations.fast; }

        if(current-index == 0) : Settings {
            close => {
                root.close();
            }

            width: root.width;
        }
    }
 }
