import { Button } from "../widgets/widgets.slint";
import { Carousel } from "../widgets/widgets.slint";
import { GroupBox } from "../widgets/group_box.slint";
import { Images } from "../images.slint";
import { NalufxTheme } from "../components/themes/index.slint";
import { Page } from "page.slint";
import { Slider } from "../widgets/widgets.slint";

export component About inherits Page {
    Rectangle {
        width: 100%;
        height: 100%;
        VerticalLayout {
            width: 100%;
            height: 100%;
            spacing: 0;

            Rectangle {
                horizontal-stretch: 1;
                vertical-stretch: 1;
            }

            Rectangle {
                width: 100%;
                height: 100%;
                VerticalLayout {
                    preferred-width: 100%;
                    preferred-height: 100%;
                    alignment: center;
                    spacing: 0;
                    GroupBox {
                        HorizontalLayout {
                            alignment: center;
                            padding-left: 0;
                            padding-right: 0;
                            VerticalLayout {
                                spacing: NalufxTheme.spaces.small;
                                alignment: center;
                                Rectangle {
                                    // Container for the responsive image
                                    width: 100%;
                                    height: 100px;
                                    clip: true; // Ensure content respects the bounds

                                    Image {
                                        width: parent.width * 0.7618;
                                        height: parent.height * 0.7618;
                                        preferred-height: 200px;
                                        source: Images.nalufx-banner;
                                        image-fit: contain; // Ensure the image fits within the container
                                    }
                                }

                                Text {
                                    horizontal-alignment: center;
                                    text: "Finance for the rest of us.";
                                    color: NalufxTheme.palette.secondary;
                                    font-size: NalufxTheme.typography.header-item-light.size.desktop;
                                    font-weight: NalufxTheme.typography.header-item-light.weight;
                                }

                                Text {
                                    horizontal-alignment: center;
                                    text: "© Copyright 2024 - Sebastien Rousseau. All rights reserved.";
                                    color: NalufxTheme.palette.on-primary;
                                    font-size: NalufxTheme.typography.overline.size.desktop;
                                    font-weight: NalufxTheme.typography.overline.weight;
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
