import { Theme } from "../theme.slint";
import { Images } from "../images.slint";
import { Page } from "page.slint";
import { Button } from "../widgets/widgets.slint";
import { GroupBox } from "../widgets/group_box.slint";
import { Divider } from "../widgets/widgets.slint";

export component About inherits Page {
    Rectangle {
        width: 100%;
        height: 100%;

        VerticalLayout {
            width: 100%;
            height: 100%;
            spacing: Theme.spaces.medium;

            // Top Spacer to push content towards the middle
            Rectangle {
                vertical-stretch: 1;
            }

            // Centred content container
            Rectangle {
                width: 100%;
                height: 100%;
                VerticalLayout {
                    width: 100%;
                    height: 100%;
                    alignment: center;
                    spacing: Theme.spaces.small;

                    GroupBox {
                        width: 100%;
                        VerticalLayout {
                            spacing: Theme.spaces.small;
                            alignment: center;

                            Image {
                                preferred-height: 100px;
                                source: Images.nalufx-banner;
                            }

                            Divider {
                                type: "centered";
                                horizontal_alignment: "center";
                            }

                            Text {
                                horizontal-alignment: center;
                                text: "Finance for the rest of us.";
                                color: Theme.palette.teal;
                                font-size: Theme.typo.header-item.size;
                                font-weight: Theme.typo.header-item.weight;
                            }
                            Text {
                                horizontal-alignment: center;
                                text: "© Copyright 2024 - Sebastien Rousseau. All rights reserved.";
                                color: Theme.palette.white;
                                font-size: Theme.typo.label-light.size;
                                font-weight: Theme.typo.label-light.weight;
                            }
                        }
                    }
                }
            }
        }
    }
}
