import { Page } from "page.slint";
import { GroupBox, Value, ValueDisplay, BarChart, Button, DropdownButton, ToggleButton } from "../widgets/widgets.slint";
import { Images } from "../images.slint";
import { Theme } from "../theme.slint";

export global UsageAdapter {
    in property <string> title: "Insight Overview";
    in property <[Value]> overview-model: [
        {
            value: 16.41,
            title: "Daily",
            unit: "$",
        },
        {
            value: 15.23,
            title: "Weekly",
            unit: "$",
        }
    ];
    in property <[float]> model: [
        10.0,
        9.0,
        11.0,
        12.0,
        8.0,
        14.0,
        9.0,
        16.0,
        18.0,
        12.0,
        11.0,
        14.0,
        12.0,
        16.0
    ];
    in property <float> min: 0.0;
    in property <float> max: 24.0;
}

export component Usage inherits Page {
    in property <string> title <=> UsageAdapter.title;
    in property <[Value]> overview-model <=> UsageAdapter.overview-model;
    in property <[float]> model <=> UsageAdapter.model;
    in property <float> min <=> UsageAdapter.min;
    in property <float> max <=> UsageAdapter.max;
    in-out property <string> selectedDropdownItem: "Select an option";

    GroupBox {
        title: root.title;

        Rectangle {
            width: 66px;
            height: 100%;
            clip: true;

            VerticalLayout {
                alignment: space-between;
                height: 180px;
                // Button Icon
                Button {
                    iconCenter: Images.arrow-right;
                    iconTextSpacing: 0pt;
                    clicked => {
                        // Handle button click event for "1M"
                    }
                }

                // Button Text
                Button {
                    buttonText: "1M";
                    clicked => {
                        // Handle button click event for "1M"
                    }
                }

                // Toggle button
                ToggleButton {
                    background: Theme.palette.transparent;
                    checked: false;
                }

                // Dropdown button
                // DropdownButton {
                //     background: Theme.palette.transparent;
                //     menuItems: ["Option 1", "Option 2", "Option 3"];
                //     selectedItem: root.selectedDropdownItem;
                // }
            }
        }

        Rectangle {
            BarChart {
                preferred-width: 100%;
                preferred-height: 100%;
                model: root.model;
                min: root.min;
                max: root.max;
                active: root.active;
            }

            VerticalLayout {
                alignment: start;
                ValueDisplay {
                    model: overview-model;
                    transparent-background: true;
                    alternative-colors: true;
                    active: root.active;
                }
            }
        }
    }
}
