import { Button } from "../widgets/widgets.slint";
import { Carousel } from "../widgets/widgets.slint";
import { GroupBox } from "../widgets/group_box.slint";
import { Images } from "../images.slint";
import { NalufxTheme } from "../widgets/widgets.slint";
import { Page } from "page.slint";
import { Slider } from "../widgets/widgets.slint";

export global StocksAdapter {
    in property <string> title: "Stocks";
}

export component Stocks inherits Page {
    in property <string> title <=> StocksAdapter.title;

    GroupBox {
        title: root.title;

        Rectangle {
            width: 100%;
            height: 100%;
            VerticalLayout {
                preferred-width: 100%;
                preferred-height: 100%;
                spacing: 0;
                padding: 0;
                alignment: center;

                GroupBox {
                    HorizontalLayout {
                        alignment: center;
                        spacing: 0;
                        padding: 0;
                        Carousel {
                            background: NalufxTheme.palette.transparent;
                            width: Math.min(root.width - 2 * NalufxTheme.spaces.small, 150px * self.sources.length);
                            height: Math.min(root.height - 2 * NalufxTheme.spaces.small, 150px);
                            sources: [
                                Images.aapl-logo,
                                Images.amzn-logo,
                                Images.googl-logo,
                                Images.msft-logo,
                                Images.tsla-logo,
                                Images.hsbc-logo,
                                Images.meta-logo
                            ];
                            titles: [
                                "Apple Inc. (AAPL)",
                                "Amazon.com, Inc. (AMZN)",
                                "Alphabet Inc. (GOOGL)",
                                "Microsoft Corporation (MSFT)",
                                "Tesla, Inc. (TSLA)",
                                "HSBC Holdings plc (HSBC)",
                                "Meta Platforms, Inc. (META)",
                            ];
                            descriptions: [
                                "Description 0",
                                "Description 1",
                                "Description 2",
                                "Description 3",
                                "Description 4",
                                "Description 5",
                                "Description 6",
                            ];
                            focus-main: true;
                            type: Rotary;
                            clicked => {
                                // Handle click event
                            }
                        }
                    }
                }
            }
        }
    }
}
