import { Theme } from "../../theme.slint";
import { ButtonCore } from "./button_core.slint";
import { StateLayer } from "../../components/state_layer.slint";

/**
 * RadioButton Component
 *
 * A circular radio button with a checked state.
 * This component provides visual feedback for the checked state.
 */
export component RadioButton {
    /**
     * Indicates if the radio button is checked.
     */
    in property <bool> checked;

    /**
     * Event triggered when the radio button is clicked.
     */
    callback clicked <=> i-touch-area.clicked;

    states [
        checked when checked : {
            i-container.border-color: Theme.palette.lemon-green;
            i-indicator.background: Theme.palette.lemon-green;
        }
    ]

    min-height: 18px;
    width: self.height;

    i-container := Rectangle {
        border-color: Theme.palette.indigo;
        border-width: 2px;
        border-radius: self.height / 2;

        animate border-color { duration: Theme.durations.fast; }

        i-indicator := Rectangle {
            height: parent.height - 4 * parent.border-width;
            width: self.height;
            border-radius: self.height / 2;

            animate background { duration: Theme.durations.fast; }
        }
    }

    i-touch-area := TouchArea {}
}
