import { NalufxTheme } from "../components/themes/index.slint";
import { ToggleButton } from "../components/button/toggle_button.slint";
import { Theme, ThemeMode } from "../components/themes/color_scheme.slint";
import { Images } from "../images.slint";

export global HeaderAdapter {
    in-out property <string> date: "Loading date...";
    in-out property <string> time: "Loading time...";
    in-out property <string> time-suffix: "Loading suffix...";
    in property <image> logo: Images.nalufx-logo;
    in-out property <string> description: "AI Insights for Funds Management and Research";
    in-out property <ThemeMode> current-theme: ThemeMode.Light;
}

export component Header {
    in property <string> date <=> HeaderAdapter.date;
    in property <string> time <=> HeaderAdapter.time;
    in property <string> time-suffix <=> HeaderAdapter.time-suffix;
    in property <image> logo <=> HeaderAdapter.logo;
    in property <string> description <=> HeaderAdapter.description;
    in-out property <ThemeMode> current-theme <=> HeaderAdapter.current-theme;

    callback theme-toggled();

    min-height: 50px;
    vertical-stretch: 0;

    HorizontalLayout {
        padding: 20px;
        spacing: 5px;

        // Date
        Rectangle {
            horizontal-stretch: 1;
            vertical-stretch: 1;
            Text {
                x: 0px;
                color: NalufxTheme.palette.white;
                text: date;
                font-weight: NalufxTheme.typography.header-item.weight;
            }
        }

        // Logo and Description
        Rectangle {
            horizontal-stretch: 1;
            vertical-stretch: 1;

            VerticalLayout {
                padding: 20px;
                spacing: 5px;

                Image {
                    height: 60px;
                    source: logo;
                    padding: 5px;
                }

                Text {
                    color: NalufxTheme.palette.white;
                    text: description;
                    horizontal-alignment: center;
                    font-weight: NalufxTheme.typography.header.weight;
                    width: root.width / 2;
                }
            }
        }

        // Time and Theme Toggle
        Rectangle {
            horizontal-stretch: 1;
            vertical-stretch: 1;

            Text {
                x: i-time-suffix.x - 5px - self.width;
                horizontal-alignment: right;
                color: NalufxTheme.palette.white;
                text: time;
                font-weight: NalufxTheme.typography.header-item-light.weight;
            }

            i-time-suffix := Text {
                x: parent.width - self.width;
                horizontal-stretch: 0;
                color: NalufxTheme.palette.white;
                text: time-suffix;
                font-weight: NalufxTheme.typography.header-item-light.weight;
            }
        }

        Rectangle {
            width: 40px;
            height: 40px;
            background: NalufxTheme.palette.transparent;

            ToggleButton {
                width: parent.width;
                height: parent.height;
                background: NalufxTheme.palette.transparent;
                checked: root.current-theme == ThemeMode.Dark;

                toggled => {
                    root.current-theme = self.checked ? ThemeMode.Dark : ThemeMode.Light;
                    root.theme-toggled();
                }
            }

            Text {
                text: root.current-theme == ThemeMode.Light ? "🌙" : "🔆";
                color: root.current-theme == ThemeMode.Light ? NalufxTheme.palette.system-yellow : NalufxTheme.palette.system-blue;
                font-size: NalufxTheme.typography.label-light.size.desktop;
                horizontal-alignment: center;
                vertical-alignment: center;
            }
        }
    }
}