import { Theme } from "../theme.slint";
import { Images } from "../images.slint";

export global HeaderAdapter {
    in-out property <string> date: "Loading date...";
    in-out property <string> time: "Loading time...";
    in-out property <string> time-suffix: "Loading suffix...";
    in property <image> logo: Images.nalufx-logo;
    in-out property <string> description: "AI Insights for Funds Management and Research";
}

export component Header {
    in property <string> date <=> HeaderAdapter.date;
    in property <string> time <=> HeaderAdapter.time;
    in property <string> time-suffix <=> HeaderAdapter.time-suffix;
    in property <image> logo <=> HeaderAdapter.logo;
    in property <string> description <=> HeaderAdapter.description;

    min-height: 50px;
    vertical-stretch: 0;

    HorizontalLayout {
        padding: 20px;
        spacing: 5px;

        Rectangle {
            horizontal-stretch: 1;
            vertical-stretch: 1;

            Text {
                x: 0px;
                color: Theme.palette.white;
                text: date;
                font-size: Theme.typo.header-item.size;
                font-weight: Theme.typo.header-item.weight;
            }
        }

        Rectangle {
            horizontal-stretch: 1;
            vertical-stretch: 1;

            VerticalLayout {
                padding: 20px;
                spacing: 5px;

                Image {
                    height: 60px;
                    source: logo;
                    padding: 5px;
                }

                Text {
                    color: Theme.palette.white;
                    text: description;
                    horizontal-alignment: center;
                    font-size: Theme.typo.header.size;
                    font-weight: Theme.typo.header.weight;
                    width: root.width / 2;
                }
            }
        }

        Rectangle {
            horizontal-stretch: 1;
            vertical-stretch: 1;

            Text {
                x: i-time-suffix.x - 5px - self.width;
                horizontal-alignment: right;
                color: Theme.palette.white;
                text: time;
                font-size: Theme.typo.header-item.size;
                font-weight: Theme.typo.header-item.weight;
            }

            i-time-suffix := Text {
                x: parent.width - self.width;
                horizontal-stretch: 0;
                color: Theme.palette.shark-gray;
                text: time-suffix;
                font-size: Theme.typo.header-item.size;
                font-weight: Theme.typo.header-item.weight;
            }
        }
    }
}
