

export global Images {
    in property <image> arrow-left: @image-url("assets/arrow-left.svg");
    in property <image> arrow-right: @image-url("assets/arrow-right.svg");
    in property <image> arrow-top: @image-url("assets/arrow-top.svg");
    in property <image> arrow-bottom: @image-url("assets/arrow-bottom.svg");
    in property <image> carret-top: @image-url("assets/carret-top.svg");
    in property <image> carret-bottom: @image-url("assets/carret-bottom.svg");
    in property <image> check: @image-url("assets/check.svg");
    in property <image> sunny: @image-url("assets/sunny.svg");
    in property <image> cloud: @image-url("assets/cloud.svg");
    in property <image> cloudy: @image-url("assets/cloudy.svg");
    in property <image> settings: @image-url("assets/settings.svg");
    in property <image> information: @image-url("assets/information.svg");
    in property <image> nalufx-banner: @image-url("assets/banner-nalufx.svg");
    in property <image> aapl-logo: @image-url("assets/aapl-logo.svg");
    in property <image> amzn-logo: @image-url("assets/amzn-logo.svg");
    in property <image> meta-logo: @image-url("assets/meta-logo.svg");
    in property <image> googl-logo: @image-url("assets/googl-logo.svg");
    in property <image> hsbc-logo: @image-url("assets/hsbc-logo.svg");
    in property <image> ma-logo: @image-url("assets/ma-logo.svg");
    in property <image> mco-logo: @image-url("assets/mco-logo.svg");
    in property <image> msft-logo: @image-url("assets/msft-logo.svg");
    in property <image> nalufx-logo: @image-url("assets/nalufx-logo.svg");
    in property <image> nvda-logo: @image-url("assets/nvda-logo.svg");
    in property <image> race-logo: @image-url("assets/race-logo.svg");
    in property <image> tsla-logo: @image-url("assets/tsla-logo.svg");
    in property <image> v-logo: @image-url("assets/v-logo.svg");
    in property <image> dashboard: @image-url("assets/dashboard.svg");
}