import { Header, HeaderAdapter, Footer, FooterAdapter } from "blocks/blocks.slint";
import { Images } from "images.slint";
import { NalufxTheme } from "components/themes/index.slint";
import { Theme, ThemeMode } from "components/themes/color_scheme.slint";

import { Menu, PageScrollView, PageContainer } from "widgets/widgets.slint";
import { MenuPage } from "pages/pages.slint";
import { Balance, Overview, Usage, UsageAdapter, Stocks, About } from "pages/pages.slint";


/// Main component representing the entire application interface
export component Main {
    in-out property <ThemeMode> current-theme: ThemeMode.Light;

    function toggle-theme() {
        self.current-theme = self.current-theme == ThemeMode.Light ? ThemeMode.Dark : ThemeMode.Light;
        Theme.mode = self.current-theme;
        Theme.update-theme();
    }

    Rectangle {
        // Set the background using a radial gradient from the theme
        background: NalufxTheme.palette.underPageBackgroundColor;

        VerticalLayout {
            padding-bottom: 25px;

            // Header component at the top of the layout
            Header {
                theme-toggled => {
                    root.toggle-theme();
                }
            }

            // Scrollable view containing multiple pages
            i-page-scroll-view := PageScrollView {
                horizontal-stretch: 1;
                vertical-stretch: 1;
                page-count: 6;  // Total number of pages

                // Overview page
                PageContainer {
                    clicked => { i-page-scroll-view.toggle-selection(self.index, self.x); }
                    index: 0;
                    selected <=> i-page-scroll-view.selection;
                    selected-width: i-page-scroll-view.selected-width;
                    selected-height: i-page-scroll-view.selected-height;
                    selected-h-offset: i-page-scroll-view.selected-h-offset;
                    Overview {}
                }

                // Usage page
                PageContainer {
                    clicked => { i-page-scroll-view.toggle-selection(self.index, self.x); }
                    index: 1;
                    selected <=> i-page-scroll-view.selection;
                    selected-width: i-page-scroll-view.selected-width;
                    selected-height: i-page-scroll-view.selected-height;
                    selected-h-offset: i-page-scroll-view.selected-h-offset;
                    Usage {}
                }

                // Balance page
                PageContainer {
                    clicked => { i-page-scroll-view.toggle-selection(self.index, self.x); }
                    index: 2;
                    selected <=> i-page-scroll-view.selection;
                    selected-width: i-page-scroll-view.selected-width;
                    selected-height: i-page-scroll-view.selected-height;
                    selected-h-offset: i-page-scroll-view.selected-h-offset;
                    Balance {}
                }

                // Stocks page
                PageContainer {
                    clicked => { i-page-scroll-view.toggle-selection(self.index, self.x); }
                    index: 4;
                    selected <=> i-page-scroll-view.selection;
                    selected-width: i-page-scroll-view.selected-width;
                    selected-height: i-page-scroll-view.selected-height;
                    selected-h-offset: i-page-scroll-view.selected-h-offset;
                    Stocks {}
                }

                // About page
                PageContainer {
                    clicked => { i-page-scroll-view.toggle-selection(self.index, self.x); }
                    index: 5;
                    selected <=> i-page-scroll-view.selection;
                    selected-width: i-page-scroll-view.selected-width;
                    selected-height: i-page-scroll-view.selected-height;
                    selected-h-offset: i-page-scroll-view.selected-h-offset;
                    About {}
                }
            }

            // Footer component at the top of the layout
            Footer {}
        }

        // Menu component overlaying the main content
        i-menu := Menu {
            stays-open: true;
            preferred-width: 100%;
            preferred-height: 100%;
            start-y: 35px;
            end-y: 75px;
            menu-width: root.width / 2;
            menu-height: root.height - 75px;

            // Reset menu page index when opened
            opend => {
                i-menu-page.current-index = 0;
            }

            // Menu page component
            i-menu-page := MenuPage {
                close => {
                    i-menu.hide();
                }

                preferred-width: 100%;
                preferred-height: 100%;
            }
        }
    }
}

