export struct Palette {
    // Primary colors
    primary: brush,
    primary_light: brush,
    primary_dark: brush,

    // Secondary colors
    secondary: brush,
    secondary_light: brush,
    secondary_dark: brush,

    // Tertiary colors
    tertiary: brush,
    tertiary_light: brush,
    tertiary_dark: brush,

    // General colors
    nalufx-blue: brush,
    pure-black: brush,
    dark-deep-blue: brush,
    shark-gray: brush,
    lemon-green: brush,
    lemon-green-op10: brush,
    white: brush,
    dimmer: brush,
    transparent: brush,
    red: brush,
    orange: brush,
    yellow: brush,
    green: brush,
    mint: brush,
    teal: brush,
    cyan: brush,
    blue: brush,
    indigo: brush,
    purple: brush,
    pink: brush,
    brown: brush,
    gray: brush,
    black: brush,

    // Nalufx purple shades
    nalufx-purple-50: brush,
    nalufx-purple-100: brush,
    nalufx-purple-200: brush,
    nalufx-purple-300: brush,
    nalufx-purple-400: brush,
    nalufx-purple-500: brush,
    nalufx-purple-600: brush,
    nalufx-purple-700: brush,
    nalufx-purple-800: brush,
    nalufx-purple-900: brush,

    // Nalufx indigo shades
    nalufx-indigo-50: brush,
    nalufx-indigo-100: brush,
    nalufx-indigo-200: brush,
    nalufx-indigo-300: brush,
    nalufx-indigo-400: brush,
    nalufx-indigo-500: brush,
    nalufx-indigo-600: brush,
    nalufx-indigo-700: brush,
    nalufx-indigo-800: brush,
    nalufx-indigo-900: brush,

    // Nalufx blue shades
    nalufx-blue-50: brush,
    nalufx-blue-100: brush,
    nalufx-blue-200: brush,
    nalufx-blue-300: brush,
    nalufx-blue-400: brush,
    nalufx-blue-500: brush,
    nalufx-blue-600: brush,
    nalufx-blue-700: brush,
    nalufx-blue-800: brush,
    nalufx-blue-900: brush,

    // Lime green shades
    lime-green-50: brush,
    lime-green-100: brush,
    lime-green-200: brush,
    lime-green-300: brush,
    lime-green-400: brush,
    lime-green-500: brush,
    lime-green-600: brush,
    lime-green-700: brush,
    lime-green-800: brush,
    lime-green-900: brush,

    // Gradients
    nalufx-blue-gradient: brush,
    nalufx-brown-gradient: brush,
    nalufx-cyan-gradient: brush,
    nalufx-gray-gradient: brush,
    nalufx-green-gradient: brush,
    nalufx-indigo-gradient: brush,
    nalufx-mint-gradient: brush,
    nalufx-orange-gradient: brush,
    nalufx-pink-gradient: brush,
    nalufx-purple-gradient: brush,
    nalufx-red-gradient: brush,
    nalufx-teal-gradient: brush,
    nalufx-yellow-gradient: brush,
    nalufx-twilight-gradient: brush,
    lemon-green-gradient: brush,
    lemon-green-light-gradient: brush,
    lemon-green-radial-gradient: brush,
    dark-left-gradient: brush,
    dark-right-gradient: brush,
    ebony-radial-gradient: brush,
    bar-gradient: brush,
    alternative-bar-gradient: brush,
    alternative-light-bar-gradient: brush,
    inverted-bar-gradient: brush,
    inverted-alternative-bar-gradient: brush,
    bar-background-gradient: brush,
    tab-gradient: brush,
    background-gradient: brush,

    // Radial gradients
    nalufx-twilight-radial-gradient: brush,

    // Nalufx bar gradients
    nalufx-red-bar-gradient: brush,
    nalufx-orange-bar-gradient: brush,
    nalufx-yellow-bar-gradient: brush,
    nalufx-green-bar-gradient: brush,
    nalufx-mint-bar-gradient: brush,
    nalufx-teal-bar-gradient: brush,
    nalufx-cyan-bar-gradient: brush,
    nalufx-blue-bar-gradient: brush,
    nalufx-indigo-bar-gradient: brush,
    nalufx-purple-bar-gradient: brush,
    nalufx-pink-bar-gradient: brush,
    nalufx-brown-bar-gradient: brush,
    nalufx-gray-bar-gradient: brush,
    nalufx-twilight-bar-gradient: brush,
}

export struct Spaces {
    small: length,
    medium: length,
    large: length,
}

export struct Durations {
    fast: duration,
    medium: duration,
    slow: duration,
}

struct Font {
    size: length,
    weight: float,
}

export struct Typo {
    label: Font,
    label-light: Font,
    header: Font,
    header-item: Font,
    header-item-light: Font,
    value: Font,
    description: Font,
    description-light: Font,
    value-big: Font,
}

export global Theme {
    in property <Palette> palette: {
        primary: #0025FF,
        primary_light: #2F2AFF,
        primary_dark: #001FF7,
        secondary: #DEFB3A,
        secondary_light: #EBFC93,
        secondary_dark: #CBE600,
        tertiary: #FF69B4,
        tertiary_light: #FFB6C1,
        tertiary_dark: #FF1493,

        red: #FF453A,
        orange: #FF9F0A,
        yellow: #FFD60A,
        green: #32D74B,
        mint: #66D4CF,
        teal: #6AC4DC,
        cyan: #5AC8F5,
        blue: #0A84FF,
        indigo: #6200EE,
        purple: #BF5AF2,
        pink: #FF3761,
        brown: #AC8E68,
        gray: #98989D,
        black: #000000,

        // Primary
        nalufx-blue: #0025FF,
        pure-black: #000000,
        dark-deep-blue: #040708,
        shark-gray: #2C2F36,
        lemon-green: #DEFB3A,
        lemon-green-op10: #defb3a1a,
        white: #FFFFFF,
        dimmer: #0000007b,
        // Nalufx purple shades
        nalufx-purple-50: #F3E7FF,
        nalufx-purple-100: #E0C3FF,
        nalufx-purple-200: #CC9AFF,
        nalufx-purple-300: #B76FFF,
        nalufx-purple-400: #A24EFF,
        nalufx-purple-500: #8D2AFF,
        nalufx-purple-600: #7A00FF,
        nalufx-purple-700: #6F00F7,
        nalufx-purple-800: #6500F2,
        nalufx-purple-900: #4D00EF,

        // Nalufx indigo shades
        nalufx-indigo-50: #E8EAF6,
        nalufx-indigo-100: #C5CAE9,
        nalufx-indigo-200: #9FA8DA,
        nalufx-indigo-300: #7986CB,
        nalufx-indigo-400: #5C6BC0,
        nalufx-indigo-500: #6200EE, // Base color
        nalufx-indigo-600: #5E35B1,
        nalufx-indigo-700: #512DA8,
        nalufx-indigo-800: #4527A0,
        nalufx-indigo-900: #311B92,

        // Nalufx blue shades
        nalufx-blue-50: #EEE6FF,
        nalufx-blue-100: #D0C3FF,
        nalufx-blue-200: #AF9AFF,
        nalufx-blue-300: #896FFF,
        nalufx-blue-400: #654EFF,
        nalufx-blue-500: #2F2AFF,
        nalufx-blue-600: #0025FF,
        nalufx-blue-700: #001FF7,
        nalufx-blue-800: #0019F2,
        nalufx-blue-900: #000AEF,

        // Lime green shades
        lime-green-50: #FBFFE6,
        lime-green-100: #F4FDC0,
        lime-green-200: #EBFC93,
        lime-green-300: #E2FA63,
        lime-green-400: #DEFB3A,
        lime-green-500: #D6F800,
        lime-green-600: #CBE600,
        lime-green-700: #BBCF00,
        lime-green-800: #ACB700,
        lime-green-900: #D9D9D9,

        // Gradients
        nalufx-red-gradient: @linear-gradient(135deg, #0f0c29 0%, #33181c 25%, #592529 50%, #33181c 75%, #592529 100%),
        nalufx-orange-gradient: @linear-gradient(135deg, #0f0c29 0%, #33240f 25%, #593d19 50%, #33240f 75%, #593d19 100%),
        nalufx-yellow-gradient: @linear-gradient(135deg, #0f0c29 0%, #33300f 25%, #594d19 50%, #33300f 75%, #594d19 100%),
        nalufx-green-gradient: @linear-gradient(135deg, #0f0c29 0%, #1c3319 25%, #2e5930 50%, #1c3319 75%, #2e5930 100%),
        nalufx-mint-gradient: @linear-gradient(135deg, #0f0c29 0%, #1b3333 25%, #315959 50%, #1b3333 75%, #315959 100%),
        nalufx-teal-gradient: @linear-gradient(135deg, #0f0c29 0%, #193134 25%, #30555d 50%, #193134 75%, #30555d 100%),
        nalufx-cyan-gradient: @linear-gradient(135deg, #0f0c29 0%, #193139 25%, #305561 50%, #193139 75%, #305561 100%),
        nalufx-blue-gradient: @linear-gradient(135deg, #0f0c29 0%, #10213f 25%, #193861 50%, #10213f 75%, #193861 100%),
        nalufx-indigo-gradient: @linear-gradient(135deg, #0f0c29 0%, #1c1b40 25%, #302e66 50%, #1c1b40 75%, #302e66 100%),
        nalufx-purple-gradient: @linear-gradient(135deg, #0f0c29 0%, #2c1b40 25%, #482e66 50%, #2c1b40 75%, #482e66 100%),
        nalufx-pink-gradient: @linear-gradient(135deg, #0f0c29 0%, #33121a 25%, #59202e 50%, #33121a 75%, #59202e 100%),
        nalufx-brown-gradient: @linear-gradient(135deg, #0f0c29 0%, #33291a 25%, #59492e 50%, #33291a 75%, #59492e 100%),
        nalufx-gray-gradient: @linear-gradient(135deg, #0f0c29 0%, #333333 25%, #595959 50%, #333333 75%, #595959 100%),
        nalufx-twilight-gradient: @linear-gradient(135deg, #896fff 0%, #39316B 100%),

        // Radial gradients
        // nalufx-twilight-radial-gradient: @radial-gradient(circle, rgba(59,130,246, 0.5) 25%, #000000 100%),

        // Nalufx bar gradients
        nalufx-red-bar-gradient: @linear-gradient(180deg, #ff6b6b 0%, #ff6b6b00 100%),
        nalufx-orange-bar-gradient: @linear-gradient(180deg, #ff9e42 0%, #ff9e4200 100%),
        nalufx-yellow-bar-gradient: @linear-gradient(180deg, #ffd700 0%, #ffd70000 100%),
        nalufx-green-bar-gradient: @linear-gradient(180deg, #4caf50 0%, #4caf5000 100%),
        nalufx-mint-bar-gradient: @linear-gradient(180deg, #66ffcc 0%, #66ffcc00 100%),
        nalufx-teal-bar-gradient: @linear-gradient(180deg, #66ccff 0%, #66ccff00 100%),
        nalufx-cyan-bar-gradient: @linear-gradient(180deg, #00ffff 0%, #00ffff00 100%),
        nalufx-blue-bar-gradient: @linear-gradient(180deg, #3399ff 0%, #3399ff00 100%),
        nalufx-indigo-bar-gradient: @linear-gradient(180deg, #6666ff 0%, #6666ff00 100%),
        nalufx-purple-bar-gradient: @linear-gradient(180deg, #cc66ff 0%, #cc66ff00 100%),
        nalufx-pink-bar-gradient: @linear-gradient(180deg, #ff66b2 0%, #ff66b200 100%),
        nalufx-brown-bar-gradient: @linear-gradient(180deg, #d2a679 0%, #d2a67900 100%),
        nalufx-gray-bar-gradient: @linear-gradient(180deg, #999999 0%, #99999900 100%),
        nalufx-twilight-bar-gradient: @linear-gradient(180deg, #b399ff 0%, #b399ff00 100%),

        lemon-green-gradient: @linear-gradient(135deg, #defb3a75 0%, #defb3a00 100%),
        lemon-green-light-gradient: @linear-gradient(135deg, #DEFB3A 0%, #defb3a33 100%),
        lemon-green-radial-gradient: @radial-gradient(circle, #DEFB3A20 0%, #DEFB3A00 100%),
        nalufx-blue-gradient: @linear-gradient(135deg, #6c4bff76 0%, #6C4BFF00 100%),
        dark-left-gradient: @linear-gradient(90deg, #040708 0%, #04070875 50%, #04070800 100%),
        dark-right-gradient: @linear-gradient(90deg, #04070800 0%, #04070875 50%, #040708 100%),
        ebony-radial-gradient: @radial-gradient(circle, #100F23 0%, #1F1946 100%),
        bar-gradient: @linear-gradient(180deg, #6C4BFF 0%, #6c4bff00 100%),
        alternative-bar-gradient: @linear-gradient(180deg, #CBE600 0%, #CBE60000 100%),
        alternative-light-bar-gradient: @linear-gradient(180deg, #EBFC93 0%, #EBFC9300 100%),
        inverted-bar-gradient: @linear-gradient(180deg, #6c4bff00 0%, #6C4BFF 100%),
        inverted-alternative-bar-gradient: @linear-gradient(180deg, #CBE60000 0%, #CBE600 100%),
        bar-background-gradient: @linear-gradient(180deg, #896FFF 0%, #896FFF00 100%),
        tab-gradient: @linear-gradient(180deg, #0026ff21 0%, #0026ff01 100%),
        background-gradient: @radial-gradient(circle, #0026ff40 50%, #0025FF00 100%),
    };

    in property <Spaces> spaces: {
        small: 5px,
        medium: 10px,
        large: 20px,
    };

    in property <Durations> durations: {
        fast: 125ms,
        medium: 200ms,
        slow: 500ms,
    };

    in property <Typo> typo: {
        label-light: {
            size: 12px,
            weight: 400
        },
        label: {
            size: 12px,
            weight: 500
        },
        header: {
            size: 16px,
            weight: 600
        },
        header-item: {
            size: 18px,
            weight: 400
        },
        header-item-light: {
            size: 18px,
            weight: 200
        },
        value: {
            size: 26px,
            weight: 500
        },
        description: {
            size: 14px,
            weight: 400
        },
        description-light: {
            size: 14px,
            weight: 200
        },
        value-big: {
            size: 40px,
            weight: 200
        },
    };
}

export enum ScreenSize {
    EmbeddedSmall,
    EmbeddedMedium,
    Mobile,
    Desktop
}
